/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const superhero_Logic = require('./code/superhero-logic');

class prueba1Srv extends LCAPApplicationService {
    async init() {

        this.after('READ', 'SuperHero', async (results, request) => {
            await superhero_Logic(results, request);
        });

        return super.init();
    }
}
module.exports = {
    prueba1Srv
};